/** A passage within the story. */
export interface SnowmanPassage {

	// Properties

	/** The numeric ID of the passage. */
	readonly id: number;
	/** The name of the passage. */
	readonly name: string;
	/** The tags of the passage. */
	readonly tags: string[];
	/** The passage source code. */
	readonly source: string;

	// Functions

	/** Returns an HTML-rendered version of the passage’s source. This first runs the source
	 * code through the Underscore template parser, then runs the result through a Markdown
	 * renderer, and then finally converts bracketed links to passage links.
	 * 
	 * @param source Source
	 * @returns HTML source
	 */
	render(source: string): string;

}

/** A story comprised of a series of passages, one of which is currently displayed. */
export interface SnowmanStory {

	// Properties

	/** The name of the story. */
	readonly name: string;
	/** The ID of the first passage to be displayed. */
	readonly startPassage: number;
	/** The program that created the story. */
	readonly creator: string;
	/** The version of the program used to create the story. */
	readonly creatorVersion: string;
	/** An array of passage IDs, one for each passage viewed during the current session. */
	readonly history: number[];
	/**
	 * An object that stores data that persists across a single user session. Any other 
	 * variables will not survive the user pressing back or forward.
	 */
	state: any;
	/** The name of the last checkpoint set. If none has been set, this is an empty string. */
	readonly checkpointName: string;
	/** 
	 * If set to `true`, then any JavaScript errors are ignored – normally,
	 * play would end with a message shown to the user.
	 */
	ignoreErrors: boolean;
	/**
	 * The message shown to users when there is an error and `ignoreErrors` is not true. 
	 * Any markup in the message will be interpolated as the actual error message.
	 */
	errorMessage: string;
	/** An array of all passages, indexed by ID. */
	readonly passages: number[];
	/** An array of user-specific scripts to run when the story is begun. */
	readonly userScripts: Function[];
	/** An array of user-specific style declarations to add when the story is begun. */
	readonly userStyles: string[];
	/** If currently at a checkpoint or not. */
	readonly atCheckpoint: boolean;

	// Functions

	/** Tries to add an entry in the browser history for the current story state. Remember, only
	 * variables set on this story’s state variable are stored in the browser history.
	 * 
	 * @param name Checkpoint name, appears in history, optional
	 */
	checkpoint(name?: string): void;

	/** Returns the Passage object corresponding to either an ID or name. If none exists, then 
	 * it returns `null`.
	 * 
	 * @param idOrName ID or name of the passage
	 * @returns The passage object or `null`
	 */
	passage(idOrName: string | number): SnowmanPassage | null;

	/** Returns the HTML source for a passage. This is most often used when embedding one passage 
	 * inside another. In this instance, make sure to use `<%= ... %>` instead of `<%- ... %>` 
	 * to avoid incorrectly encoding HTML entities.
	 * 
	 * @param idOrName ID or name of the passage
	 * @returns HTML source code
	 */
	render(idOrName: string | number): string;

	/** Tries to restore the story state from a hash value generated by `saveHash()`.
	 * 
	 * @param hash Hash
	 * @returns Whether the restore succeeded
	 */
	restore(hash: string): boolean;

	/** Sets the URL’s hash property to the hash value created by `saveHash()`.
	 * 
	 * @returns Hash
	 */
	save(): string;

	/** Returns a hash value representing the current state of the story.
	 * 
	 * @returns Hash
	 */
	saveHash(): string;

	/** Displays a passage on the page, replacing the current one. If there is no passage by the
	 * name or ID passed, an exception is raised.
	 * 
	 * @param idOrName ID or name of the passage
	 * @param silent If `true`, then this will not be recorded in the story history
	 */
	show(idOrName: string | number, silent?: boolean): void;

	/** Begins playing the story. */
	start(): void;

}

/** Gets the current story.
 * 
 * @returns The current story
 */
export function getStory(): SnowmanStory {
	return (window as any).story as SnowmanStory;
}

/** Gets the current passage.
 * 
 * @returns The current passage
 */
export function getCurrentPassage(): SnowmanPassage {
	return (window as any).passage as SnowmanPassage;
}
